Repository dragonflyoss/d7y.io, pull requests merged in 2025-01, with the labels that each got.

#208 docs: add encrypted storage feature for client in v2.4 roadmap
  docs/roadmap/v2.4.md
Labels: enhancement

#209 feat: upgrade docusaurus to the latest version
  blog/2022-06-06-evolution-of-nydus/index.md
  blog/2022-11-03-dragonfly-integrates-nydus-for-image-acceleration-practice/index.md
  blog/2023-09-15-security-audit/index.md
  docusaurus.config.js
  netlify.toml
  package.json
  versioned_docs/version-v2.0.2/getting-started/quick-start/docker-compose.md
  versioned_docs/version-v2.0.2/setup/runtime/containerd/mirror.md
  versioned_docs/version-v2.0.3/getting-started/quick-start/docker-compose.md
  versioned_docs/version-v2.0.3/setup/runtime/containerd/mirror.md
  versioned_docs/version-v2.0.4/getting-started/quick-start/docker-compose.md
  versioned_docs/version-v2.0.4/setup/runtime/containerd/mirror.md
  versioned_docs/version-v2.0.5/getting-started/quick-start/docker-compose.md
  versioned_docs/version-v2.0.5/setup/runtime/containerd/mirror.md
  versioned_docs/version-v2.0.6/getting-started/quick-start/docker-compose.md
  versioned_docs/version-v2.0.6/setup/runtime/containerd/mirror.md
  versioned_docs/version-v2.0.7/getting-started/quick-start/docker-compose.md
  versioned_docs/version-v2.0.7/setup/runtime/containerd/mirror.md
  versioned_docs/version-v2.0.8/getting-started/quick-start/docker-compose.md
  versioned_docs/version-v2.0.8/setup/runtime/containerd/mirror.md
  versioned_docs/version-v2.0.9/getting-started/quick-start/docker-compose.md
  versioned_docs/version-v2.0.9/setup/runtime/containerd/mirror.md
  versioned_docs/version-v2.1.0/getting-started/quick-start/docker-compose.md
  versioned_docs/version-v2.1.0/setup/runtime/containerd/mirror.md
  videos/sessions/en/2023-02-15.md
Labels: enhancement

#215 fix: home page copywriting error
  src/pages/index.js
Labels: bug

#222 feat: add leech document
  docs/advanced-guides/leech.md
  sidebars/docs.js
Labels: documentation
