Repository dragonflyoss/d7y.io, pull requests merged in 2025-02, with the labels that each got.

#221 feat: add rate limit document
  docs/advanced-guides/rate-limit.md
  docs/resource/advanced-guides/rate-limit/rate-limit.webp
  sidebars/docs.js
Labels: documentation

#219 feat: add document pip
  docs/operations/integrations/pip.md
  docs/resource/operations/integrations/installing-packages.png
  docs/resource/operations/integrations/pip-p2p.png
  sidebars/docs.js
Labels: documentation

#220 feat: add client introduction
  docs/operations/deployment/applications/client.md
  docs/resource/operations/deployment/applications/client/client-back-to-source-download.svg
  docs/resource/operations/deployment/applications/client/client-download.svg
Labels: documentation

#225 docs: add audit logging for v2.4 roadmap
  docs/roadmap/v2.4.md
Labels: documentation

#227 docs(reference/configuration/client): add request rate limit for client's grpc server
  docs/reference/configuration/client/dfdaemon.md
Labels: documentation

#228 docs: add HTTPS and JWT configuration for Security Best Practice
  docs/operations/best-practices/security.md
  docs/reference/configuration/manager.md
  netlify.toml
Labels: documentation, enhancement

#229 docs: add doos attacks document
  docs/advanced-guides/rate-limit.md
  docs/operations/best-practices/security.md
Labels: documentation

#231 docs: add preheat by Self-Signed Certificate
  docs/operations/best-practices/security.md
  package.json
Labels: documentation

#232 fix: preheat document
  docs/advanced-guides/preheat.md
Labels: bug

#234 docs: optimize security documents
  docs/operations/best-practices/observability/tracing.md
  docs/operations/best-practices/security.md
Labels: documentation
